#!/usr/bin/env bash
# Performing a 301 moved permanently

# Update and upgrade packages
sudo apt-get -y  update
sudo apt-get -y upgrade

# Install nginx
sudo apt-get -y install nginx

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\t\trewrite ^\/redirect_me https:\/\/github.com\/Preshladyp permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
