#!/usr/bin/env bash
# Customising a 404 page

# Update and upgrade packages
sudo apt-get -y  update
sudo apt-get -y upgrade

# Install nginx
sudo apt-get -y install nginx

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\t\trewrite ^\/redirect_me https:\/\/github.com\/Preshladyp permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_service;\n\terror_page 404 \/404.html;\n\t\location = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#Restart nginx after implementing changes

sudo service nginx restart
