#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# Update packages
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# creating an index page
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a redirection
new_string= "server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Preshladyp permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP response header
sudo sed -i "server_name _;/a add_header x-served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
