#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# Update packages
sudo apt-get -y update

# Install nginx
sudo apt-get -y install nginx

# creating an index page
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# custom HTTP response header
comment="\# Custom HTTP response header"
old="location \/ {"
new="$old\n\t\t$comment\n\t\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
