#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend precious.tech
        bind 0*:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 134947-web-01 18.210.19.235
        server 134947-web-02 52.91.182.237
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy  restart
