#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
sudo apt-get -y install software-properties-common

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm

# Add the HAProxy repository and install HAProxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy

#Haproxy configuration
balancer="\
frontend haproxy_balancer
        bind *:80
	mode htpp
        default_backend load servers

backend loadservers
        balance roundrobin
        server 134947-web-01 18.210.19.235:80 check
        server 134947-web-02 52.91.182.237:80 check
"

# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy  restart
