#!/usr/bin/env bash
#configure nginx server to listen for port 80 as before

# creates a symbolic link (-s option) between the Nginx configuratio
# file and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminate the first nginx process ID
kill "$ (pgrep 'nginx' | head -1)"
